### ISSUE TITLE
Cannot drop data object

### ISSUE THREAD

**Issue by NourEldin-Ali** [imixs/open-bpmn#155]
Hello,

I can't drop the a data object.

https://user-images.githubusercontent.com/61513661/214795781-911375d6-9f50-4984-b2f7-abe19e8e34df.mp4

**Comment by rsoika** [comment]
Hi, @NourEldin-Ali , yes the context menu functions are not yet implemented.
But I think what you have found is regarding the context menu only - right? 
I will add a new Issue regarding this feature.

**Comment by rsoika** [comment]
This problem is already solved with the latest version so I will close this issue.
But still we have an issue regarding context menu which is not supported in our VS-Code integration. This can hopefully fixed in the next release.
