### ISSUE TITLE
Change size of the tasks aren't save

### ISSUE THREAD

**Issue by NourEldin-Ali** [imixs/open-bpmn#162]
We can change the size of the tasks, but after the reset modelstate the task undo the change of size. 

Note: only "task" in the tasks save the change of the size, but the other tasks no.

https://user-images.githubusercontent.com/61513661/215152350-5885079d-831d-4635-9fdb-cb532861be41.mp4

**Comment by rsoika** [comment]
Hi @NourEldin-Ali ,
yes you are right. It seems to me that all sub classes of the task are affected. I will investigate into this.

**Comment by rsoika** [comment]
fixed
