### ISSUE TITLE
Properties are not modified in the property panel

### ISSUE THREAD

**Issue by NourEldin-Ali** [imixs/open-bpmn#164]
I changed the name of the task from the property panel; it was changed and show the new name of the task, but if I go to the property panel the name wasn't change, and after add new item (or the modelstate was reset) it changed in the panel.

https://user-images.githubusercontent.com/61513661/215467606-e710fc1b-2b81-4c59-ac8e-05df4f64c62f.mp4

**Comment by rsoika** [comment]
Yes, you are right. This is still a bug needed to be fixed

**Comment by rsoika** [comment]
Finally I fixed this issue - took me some while after I realized that I simply deleted one line of code without any reason.....
