### ISSUE TITLE
Error in save the model on windows

### ISSUE THREAD

**Issue by NourEldin-Ali** [imixs/open-bpmn#249]
Error in saving model in windows 11:

I changed the code in open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/model/BPMNSourceModelStorage.java 
From:
```java
try {
   // check protocol
    if (!uri.contains("://")) {
           uri = "file://" + uri;
     }
      java.net.URI targetURI = new URI(uri);
      model.save(targetURI);
} catch (URISyntaxException e) {
      logger.error("Invalid Target URI: " + e.getMessage());
}
``` 
To:
```java
try {
     File f = new File(uri);
      java.net.URI targetURI =f.toURI();
     model.save(targetURI);
} catch (Exception e) {
     logger.error("Invalid Target URI: " + e.getMessage());
}
``` 

I tried on windows 11 and on linux using docker and it works

**Comment by rsoika** [comment]
Hm, you code does not work for me in Linux

The uri looks for example like this:

`file:///home/rsoika/git/open-bpmn-vscode-integration/open-bpmn.vscode/workspace/imixs-test.bpmn`

calling
 
```java
File f = new File(uri);
java.net.URI targetURI =f.toURI();
```

My final solution will look this:

```java
        // compute target URI - see Issue #249
        logger.info("origin uri=" + uri);
        if (uri.startsWith("file://")) {
            uri = uri.substring(7);
        }
        File f = new File(uri);
        URI targetURI = f.toURI();
        logger.info("target uri=" + targetURI);

        model.save(targetURI);
```


Results in a URI like this one:

`file:/home/rsoika/git/open-bpmn/file:/home/rsoika/git/open-bpmn-vscode-integration/open-bpmn.vscode/workspace/imixs-test.bpmn`

**Comment by rsoika** [comment]
the new implementation solves the issue.
The problem was related to the 'Save As' option with provides a new URI with the 'file://' prefix. This prefix is not part of the usual `SourceURI`. The issue is now solved within the Open-BPMN meta model which is the better solution

**Comment by rsoika** [comment]
I thought my new implementation solved the problem but this seems not be the case for windows 11.
Very strange......
I guess your solution is the right one
