### ISSUE TITLE
How to configure DIFF Editor for VS-Code

### ISSUE THREAD

**Issue by rsoika** [imixs/open-bpmn#314]
Find this discussion:

https://github.com/microsoft/vscode/issues/138525#issuecomment-1847679100

We need to add some genera documentation how to configure vs-code correctly to compere bpmn files

**Comment by cweijan** [comment]
I found the final solution, just specify filenamePattern for the file.

```json
{
	"viewType": "viewType",
	"displayName": "Custom Editor",
	"selector": [
		{
			"filenamePattern": "file:/**/*.ext"
		}
	]
}
```

**Comment by rsoika** [comment]
@cweijan thanks for your help!

I added a page to the Open-BPMN Project site: https://www.open-bpmn.org/vs-code.html
