### ISSUE TITLE
Add new AutoAlign Action

### ISSUE THREAD

**Issue by rsoika** [imixs/open-bpmn#320]
Add new AutoAlign Action that aligns all bpmn elements of a diagram to the grid.

This method can be used to fix corrupted layouts

**Comment by zarnejo-exers** [comment]
Will this also include the auto-layout of the lines so they would not cross over each other?

**Comment by rsoika** [comment]
Hi @zarnejo-exers , it is not a routing feature. I would like to have a better routing algorithm, but for the moment we do not have such a feature. But with next release 1.2.0 modeling is much more easy as we have a new Helperline feature. So stay tuned ;-)

**Comment by zarnejo-exers** [comment]
This is noted.
Thank you very much for your replies. Appreciated!
