### ISSUE TITLE
Review of general project setup

### ISSUE THREAD

**Issue by rsoika** [imixs/open-bpmn#35]
This issue is about a short general review of the project setup. It is more or less a copy from the workflow-example. The main question is: Is the project structure generally wrong in some places? This review is not about code but more about the construction of client and server parts. 

The OpenBPMN project consists now of 3 main modules

- [open-bpmn.glsp-client](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.glsp-client) - contains glsp client implementation (nodejs)
- [open-bomn.glsp-server](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.glsp-server) - contans the glsp server part (java)
- [open-bpmn.metamodel](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.metamodel) - this module is not part of the review, it contains GLSP independent code to read, parse and write BPMN 2.0 files

In the current master branch we have 2 GLSP dependencies which now both revere to development versions of GLSP

 - for the glsp-client part we use the Version 0.10.0-next.385713d.170 - because of improved Routing behaviour
 - for the glsp-server part we are now using 0.10.0-SNAPSHOT - because of the new api to implement SourceModelStorage

We need a general review of these two modules and its setup regarding dependencies and structure:

[The open-bpmn.glsp-client](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.glsp-client):

As I am personally not very familiar with NodeJS, the client part is for me the most critical part in development. At the moment the client part of the project is working well and we have no issues with compiling. But still the main question is, if the nodejs setup in general is ok or if you see any things which should be changed?

- [ ] is the main package.json file ok?
- [ ] is the lerna.json file ok? 
- [ ] is the tsconfig.json ok?
- [ ] are there any issues regarding the setup of the files 'package.json' and 'tsconfig.json' within the modules (app, glsp, model, properties and theia)

[The open-bpmn.glsp-server](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.glsp-server):

The glsp server part is not such a big problem as the client part is, because I am familiar with java very well. But the last major change was the upgrade to glsp-server version 0.10.0-SNAPSHOT which is maybe not a good moment? But we need to implement the `SourceModelStorage` and the `GFactory` to make progress on the server side. 

The part where I'm still unsure is the package [org.openbpmn.glsp](https://github.com/imixs/open-bpmn/tree/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp). If you take a very quick look at it, do you find things that are generally wrong? A deep analysis makes no sense as this is all work under progress. But:

- [ ] Makes the [BPMNServerLauncher](https://github.com/imixs/open-bpmn/blob/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/BPMNServerLauncher.java) sense?
- [ ] Is the split between the [BPMNDiagramModule](https://github.com/imixs/open-bpmn/blob/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/BPMNDiagramModule.java) and the [BPMNDiagramConfiguation](https://github.com/imixs/open-bpmn/blob/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/BPMNDiagramConfiguration.java) a recommended way to implement the main layer?

**Comment by tortmayr** [comment]
Hi @rsoika, 
I did a short review of the current code base focusing mostly on the `open-bpmn.glsp.client`and the overall project setup/structure. In general, the setup looks good to me and I couldn't identify any major issues or bad practices. I found a couple of issues regarding the client setup that could be improved but other than that everything looks fine to me. I also used this opportunity to get a sneak peak of the current state of the open bpmn editor in action :wink:. Looks amazing so far. Great job!

# open-bpmn.glsp-client

## General

-   **Public vs. Private packages:**
    Currently you have declared all packages as private. I would assume that you plan to publish your packages to npm at some point so that other people can consume the open-bpmn packages. In general, I would only mark packages as private that are definitely never intended for publishing. For this project I would only keep the private modifier for the parent meta package (i.e. the root `package.json`) and the `open-bpmn-app`.

    You are using the `@open-bpmn` scope for your packages. In NPM a package scope always refers to a [npm organization](https://docs.npmjs.com/organizations). This means you need to create a new organization called `open-bpmn` so that you can later publish your packages. I would recommend to do this right away, even if you are not planning to publish any time soon. Creating a public organization is completely free and by registering your organization early you can ensure that nobody else claims your namespace.

    Each package should contain a README.md file and a `license` property in the `package.json`. NPM
    uses these files to display the package description.

-   **Licensing**
    What license are you planing to use for this project? To me this is currently unclear. Parts of the packages seem to be licensed with EPL2.0/GPL-2.0 (i.e. the GLSP License) other packages mention GPL-3.0.

    You should decide for one LICENSE and use it consistently i.e. update the `license` property of all  your `package.json`s. In addition, you should adapt the auto-generated copyright headers of ESLint. Currently the default Eclipse GLSP Header (with EclipseSource as author) is added. This can be done by customizing the `.eslintrc.js` file.

    If you don't want to use the ESLint header plugin at all you can turn it of with:

    ```js
    /** @type {import('eslint').Linter.Config} */
    module.exports = {
        extends: '@eclipse-glsp',
        parserOptions: {
            tsconfigRootDir: __dirname,
            project: 'tsconfig.json'
        },
        rules: {
            'header/header': 'off'
        }
    };
    ```

    Alternatively, you can also add a custom templates e.g:

    ```js
    /** @type {import('eslint').Linter.Config} */
    const year = new Date().getFullYear();
    module.exports = {
        extends: '@eclipse-glsp',
        parserOptions: {
            tsconfigRootDir: __dirname,
            project: 'tsconfig.json'
        },
        rules: {
            'header/header': [
                2,
                'block',
                [
                    {
                        pattern: '[\n\r]+ \\* Copyright \\([cC]\\) \\d{4}(-\\d{4})? .*[\n\r]+',
                        template: `*******************************************************************************
    * Copyright (c) ${year} Imixs Workflow and others.
    *
    * Your
    * Custom
    * License
    * Text
    *******************************************************************************`
                    }
                ]
            ]
        }
    };
    ```

-   **Eclipse GLSP Config**
    In GLSP we maintain a [shared configuration package](https://github.com/eclipse-glsp/glsp/tree/master/packages) for Typescript based projects. This project offers base configurations for the ts.config, ES lint configuration, Prettier configuration and Mocha (for unit testing). Reusing this in your project is perfectly fine and I just wanted to let you know that you can customize almost every aspect of the configuration for your needs. Since you are new to node and yarn sticking with the provided default values surely is a good option. Just be aware that you can easily make customizations if you need to, in the future. Just for completeness here are the entry points
    to the configuration files that you implicitly use with the `@eclipse-glsp/config package`:

    -   ts.config: https://github.com/eclipse-glsp/glsp/blob/master/packages/ts-config/tsconfig.json
    -   .eslintrc.js: https://github.com/eclipse-glsp/glsp/blob/master/packages/eslint-config/index.js
    -   .prettierrc: https://github.com/eclipse-glsp/glsp/blob/master/packages/prettier-config/index.json
    -   .mocharrc.json: https://github.com/eclipse-glsp/glsp/blob/master/packages/mocha-config/.mocharc.json

-   **Update to latest nightly**
    It looks to me like the mix of nightly versions is a bit inconsistent. In particular the server version is not entirely in sync with the client version. So far this doesn't seem to cause any issues. However, I would recommend to update all glsp packages to the latest nightly/next version to ensure a consistent state. While you are at it you should also update your Theia dependencies to `1.24.0` as this is also the version used by the nightly `@eclipse-glsp/theia-integration` package.

## Root package.json

> is the main package.json file ok?

Yes, the root `package.json` is ok. I only noticed a couple of minor issues:

-   **Resolutions:**
    The `@eclipse-glsp/protocol` package should be part of the resolutions block as well. Just to make sure
    it doesn't get out of sync with the client package.

-   **Dependencies/Peer dependencies**
    The root `package.json` is a meta parent package. As such it doesn't make sense to declare `dependencies` or `peerDependencies` here. Only dependencies need for the dev setup i.e. `devDependencies` should be declared here.

    I would suggest to:

    -   Remove the `@eclipse-glsp/client` dependency here and add it to the package(s) that actually import code from it.
    -   Remove `react` and `react-dom` from the `peerDependencies` and add them as peerDependency to the package that actually depends on them. Should be `open-bpmn-properties` as far as I can see.
    -   Move `typescript` into the `devDependencies` block.

## lerna.json

> is the lerna.json file ok?

Yes, the lerna.json file is perfectly fine. Only one slight improvement could be made here:
I would also configure npm as publish registry. Otherwise the default yarn public registry will be used and we have encountered issues with
this registry in the past.

```
{
  "version": "0.1.0",
  "useWorkspaces": true,
  "npmClient": "yarn",
  "command": {
    "run": {
      "stream": true
    }
  },
  "publish": {
    "registry": "https://registry.npmjs.org/"
  }
}
```

### ts.config

> is the tsconfig.json ok?

All `ts.config` files look OK to me.

### Additional issues

-   `open-bpmn-glsp (package.json`:
    -   Has unused dependencies to jsonforms/react. Should be removed.
    -   The "files" section references a `build` directory which does not exist.
    -   Marked as `private`. (See also general comment about publishing)
-   `open-bpmn-model (package.json`:
    -   The package uses code from `@eclipse-glsp/client`. Should be added as dependency here.
    -   The "files" section references a `build` directory which does not exist.
    -   Marked as `private`. (See also general comment about publishing)
-   `open-bpmn-properties (package.json`:
    -   The "files" section references a `build` directory which does not exist.
    -   Marked as `private`. (See also general comment about publishing)

# open-bpmn.glsp-server

> Makes the BPMNServerLauncher sense?

Yes, the `BPMNServerLauncher` implementation is perfectly fine and follows the default pattern that we use to implement
project specific server launchers.

> Is the split between the BPMNDiagramModule and the BPMNDiagramConfiguration a recommended way to implement the main layer?

Yes, this split is the recommended way to implement the main layer.

> If you take a very quick look at it, do you find things that are generally wrong?

I quickly parsed through the code but could not find anything hat is implemented wrong or flawed.

**Comment by rsoika** [comment]
@tortmayr  ok, thanks a lot for that review! I will adapt your suggestions.
