### ISSUE TITLE
How to allign BPMN elements in GLSP horizontal

### ISSUE THREAD

**Issue by rsoika** [imixs/open-bpmn#44]
In BPMN there are in general only 3 graphical element types
- task (rounded corner rectangle)
- event (circle)
- gateway (diamond)

The difficult part is that the event and gateway elements have the label outside of the shape and the task has the label inside.

The problem I am faced with is the fact that the label of an event is not relevant for its position and dimensions. If you look at the following picture you see 3 elements which are horizontal aligned. The position of the event (green circle) is x=55, y=50. The position of the first task element is x=160, y=43

![image](https://user-images.githubusercontent.com/1339124/168492755-e4fbae8c-60c2-4c26-9c0f-8c9feaa3a804.png)

The y-position of the start event is a little bit higher (50) than the y-position of the task (43)

The corresponding part in a BPMN file looks like this:

```xml
      <bpmndi:BPMNShape id="BPMNShape_StartEvent_1" bpmnElement="StartEvent_1">
        <dc:Bounds height="36.0" width="36.0" x="70.0" y="50.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_1" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="14.0" width="58.0" x="59.0" y="86.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_ManualTask_1" bpmnElement="ManualTask_1" isExpanded="true">
        <dc:Bounds height="50.0" width="110.0" x="160.0" y="43.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_2" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="14.0" width="79.0" x="175.0" y="61.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_UserTask_1" bpmnElement="UserTask_1" isExpanded="true">
        <dc:Bounds height="50.0" width="110.0" x="320.0" y="43.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_3" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="14.0" width="64.0" x="343.0" y="61.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
```

The problem is, that I am still not able to translate this into GLSP and a GNode. The task node is easy to adapt as it is covered by the RoundedCornerNodeView on the client side.The server Builder Part can be seen here [TaskNodeBuilder.java](https://github.com/imixs/open-bpmn/blob/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/elements/task/TaskNodeBuilder.java)

 But for the Event and gateway there is not corresponding View. On the client side I use a custom view implementation like this:

```javascript
@injectable()
export class EventNodeView extends ShapeView {
	render(element: EventNode, context: RenderingContext): VNode | undefined {
		if (!this.isVisible(element, context)) {
			return undefined;
		}
		let vnode: any = undefined;
			vnode = (
				<g class-sprotty-node={true} class-mouseover={element.hoverFeedback}>
					<circle r='20' cx='0' cy='0' ></circle>
					{context.renderChildren(element)}
				</g>
			);
		const subType = getSubType(element);
		if (subType) {
			setAttr(vnode, 'class', subType);
		}
		return vnode;
	}
}
```
On the server side I use a Freeform layout in my [EventNodeBuilder.java](https://github.com/imixs/open-bpmn/blob/master/open-bpmn.glsp-server/src/main/java/org/openbpmn/glsp/elements/event/EventNodeBuilder.java).
And to solve the routing problem I added a GPort on top of the circle 

But this leads to the wrong result:

![image](https://user-images.githubusercontent.com/1339124/168492535-e8472cc9-f194-400e-9343-b63d39b779d1.png)

The horizontal centre of the event element is not computed correctly because the label is included in the element bounds. 

**The questions are:**

 - what is the correct layout type to describe this GNode on the server side?
 - how could a EventNodeView look like on the client side?

**Comment by rsoika** [comment]
After thinking more about the problem, I come to the conclusion that splitting the symbol and label into two GNode elements could become the easiest and best solution. This is also because the BPMN specification foresees the possibility that the label of an event or gateway can be placed freely around the symbol. 

So only the BPMN source model treats this as one object. 

The only thing we need to solve is a way that when the user clicks on the symbol, than the label is selected too. Like with the marquee tool. Is this possible?

See this example from another tooling:
![Peek 2022-05-23 08-25](https://user-images.githubusercontent.com/1339124/169756720-b7a95fa7-08f5-4ff4-a8a6-cf7634e1d5d0.gif)

Splitting up the two elements also solves any other problems with Edge-Anchor points, alignment, layouting.....

**Comment by rsoika** [comment]
Assuming that we realize the element as two independent GNodes (Symbol and Label), the 'move' problematic can be solved in two variants:

**variant-1**
If the user moves the symbol, the label is not moved directly. The client sends then the ChangeBoundsOperation (with only the ID of the symbol), and the server automatically updates also the position of the associated label in the source model. When the GLSP Server then requests the new GModel from the GModelFactory, both - the symbol and the label - are returned with the new position.
This is what I would call a server-side solution for the move-problem.

**variant-2**
If the user clicks on the Symbol (GNode is selected), the GLSP client automatically selects also the associated Label. As a result both elements will be moved on the screen.   The client sends than the ChangeBoundsOperation containing both IDs (symbol and label). The GLSP Server simply updates the Source model with the provided new coordiantes.
This is what I would call a client-side solution for the move-problem.


In the second variant the user has a direct feedback on the screen when moving the symbol. So maybe this is more elegant?

**Comment by tortmayr** [comment]
I'd agree that the second variant is the more elegant solution and  as it offers direct client side feedback it is definitely preferable to a pure server solution.

There are a couple of potential solutions to achieve this selection behavior:

1. Customizes the Selection mouse listener (`RankedSelectMouseListener`)
2. Implement a small custom event  node selection tool on top of the existing selection tooling
3. Implement a `SelectionListener` and listen to selection changes from the `SelectionService`.

I would opt against `option 1` as the selection mouse listener's current implementation is no really designed for easy customization and you probably end up with having to re-implement a lot of the functionality.

`Option 2` also seems like a bit of overkill to me for this rather simple feature. So I think the best solution would be to go with `option 3` and implement a custom selection listener that also selects the corresponding labels for all `EventNode`s that are part of this selection:

As a prerequisite for this I would update the `EventNode` model so that it also offers a `labelId` property which stores the id of the corresponding label. This makes it easy to retrieve the corresponding label via the index. Then you could implement a simple selection listener that maps the current selection to event nodes, retrieves the corresponding labels and then dispatches a `SelectAction` for the label ids.
An (untested) implementation could look like this:

```ts
@injectable()
export class EventNodeSelectionListener implements SelectionListener {
    @inject(TYPES.IActionDispatcher)
    protected actionDispatcher: ActionDispatcher;

    selectionChanged(root: Readonly<SModelRoot>, selectedElements: string[]): void {
        const eventNodes = getElements(root.index, selectedElements, toTypeGuard(EventNode));
        if (eventNodes.length > 0) {
            const eventLabelIds = eventNodes.map(node => node.labelId);
            this.actionDispatcher.dispatch(SelectAction.create({ selectedElementsIDs: eventLabelIds }));
        }
    }
}

// bind the listener in your DI module
bind(TYPES.SelectionListener).to(EventNodeSelectionListener)

```
FYI:   `getElements` is a utility function from `smodel-utils` that can be used to retrieve corresponding model elements for a set of ids from the model index. The optional type guard can be used to filter the result set.

**Comment by rsoika** [comment]
Thanks! Following your advice with option 3 works!
![Peek 2022-05-23 23-24](https://user-images.githubusercontent.com/1339124/169908382-812f7956-980b-4d05-a5ba-7d4960131bbb.gif)

Of course, I still have to do some refactoring now. But this new approach simplifies things dramatically. I can now remove many, many lines of code that cost me many, many hours - and that's always a good indicator that the code is improving ;-)

My selection listener looks now like this: (label id can be constructed from the event node id)

```javascript
@injectable()
export class EventNodeSelectionListener implements SelectionListener {
    @inject(TYPES.IActionDispatcher)
    protected actionDispatcher: ActionDispatcher;
    selectionChanged(root: Readonly<SModelRoot>, selectedElements: string[]): void {
        const eventNodes=  getElements(root.index,selectedElements, isEventNode);
        if (eventNodes.length > 0) {
            const eventLabelIds = eventNodes.map(node => node.id+"_bpmnlabel");
            this.actionDispatcher.dispatch(SelectAction.create({ selectedElementsIDs: eventLabelIds }));
        }
    }
}
```

**Comment by rsoika** [comment]
@tortmayr  Ok, now everything works nearly perfect and I have written a short [tutotorial](https://ralph.blog.imixs.com/2022/05/26/eclipse-glsp-nodes-and-moveable-labels/). 

The only open issue now is: How can I place a GLabel horizontal centred below my symbol? 
In the moment I set the x-pos equal to the x-pos of the symbol. But this results in a strange behavior:

![Peek 2022-05-26 10-53](https://user-images.githubusercontent.com/1339124/170454357-a9ac396e-a1be-4814-b541-e709a2bd68f6.gif)

**Comment by rsoika** [comment]
@tortmayr yes, the requirements are:

Per default, the GLabel should appear below the GElement centered. If the GLabel is moved by the user the new position is stored in the source model. The code to create the Event GElements in my GModelFactory looks currently like this:

```java
            for (BPMNEvent event : process.getEvents()) {
                logger.fine("event: " + event.getName());
                BPMNPoint bpmnPoint = event.getBounds().getPosition();
                GPoint point = GraphUtil.point(bpmnPoint.getX(), bpmnPoint.getY());
                EventNodeBuilder builder = new EventNodeBuilder(event.getType(), event.getName());
                // Build the GLSP Node....
                EventNode eventNode = builder //
                        .id(event.getId()) //
                        .position(point) //
                        .build();
                entityNodes.add(eventNode);

                // now add a GLabel
                GLabel label = null;
                BPMNLabel bpmnLabel = event.getLabel();
                if (bpmnLabel != null) {
                    label = BPMNBuilderHelper.createBPMNLabel(event.getId(), eventNode.getName(),
                            bpmnLabel.getPosition().getX() - 3, bpmnLabel.getPosition().getY());
                } else {
                    // create default position
                    label = BPMNBuilderHelper.createBPMNLabel(event.getId(), eventNode.getName(), point.getX() - 3,
                            point.getY() + 36);
                }
                entityNodes.add(label);
            }
```

[Sourcecode reference](https://github.com/imixs/open-bpmn/blob/a295805ddcb2eecdb6c09761c85292201231ebdc/open-bpmn.glsp-server/src/main/java/org/openbpmn/bpmn/BPMNGModelFactory.java#L133)

If my source model already have a BPMNLabel definition I take the position from there. This works now perfectly!

If no BPMNLabel exists I define a new one and calculate the inital default position by  y+36pix (the event symbol is 36 pix height). The x-position is more or less the X-Pos of the symbol (GElement) - with an offset of -3 (my best guess).



But this is currently nonsense. And I do not really understand the behavior of a editable GLable (as you can see in the screen cast).

If I took the EclipseBPMN Plugin as a reference implementation a Diagram definition with one Start element looks like this

![image](https://user-images.githubusercontent.com/1339124/171458952-954062b4-196f-4fdf-9fb5-af88d92dc303.png)

As you can see below, the X of the label is 76 and X of the Symbol is 92 - which centers the label (width = 69) under the element 

```xml
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1">
      <bpmndi:BPMNShape id="BPMNShape_StartEvent_1" bpmnElement="StartEvent_1">
        <dc:Bounds height="36.0" width="36.0" x="92.0" y="42.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_1" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="14.0" width="69.0" x="76.0" y="78.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
    <bpmndi:BPMNLabelStyle id="BPMNLabelStyle_1">
      <dc:Font name="arial" size="9.0"/>
    </bpmndi:BPMNLabelStyle>
  </bpmndi:BPMNDiagram>
```
My current GLSP Implemenation can deal with this kind of models perfectly as I took the position from the BPMN model.

If I enter a very long name, EclipseBPMN does NOT extend the width over 70px but it breaks up the label into several lines:

![image](https://user-images.githubusercontent.com/1339124/171459361-f5904d98-3b84-452c-8f67-31d710147e83.png)

X and Y Position of the Label are now still the same. 

  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1">
      <bpmndi:BPMNShape id="BPMNShape_StartEvent_1" bpmnElement="StartEvent_1">
        <dc:Bounds height="36.0" width="36.0" x="92.0" y="42.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_1" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="42.0" width="67.0" x="77.0" y="78.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
    <bpmndi:BPMNLabelStyle id="BPMNLabelStyle_1">
      <dc:Font name="arial" size="9.0"/>
    </bpmndi:BPMNLabelStyle>
  </bpmndi:BPMNDiagram>

If I enter a very short name the width is reduced to 3 px and the position of the label is now recalculated to center the label again (x=108): 
![image](https://user-images.githubusercontent.com/1339124/171461844-31de3a43-2867-460f-9b52-d492ecebec71.png)


```xml
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1">
      <bpmndi:BPMNShape id="BPMNShape_StartEvent_1" bpmnElement="StartEvent_1">
        <dc:Bounds height="36.0" width="36.0" x="92.0" y="42.0"/>
        <bpmndi:BPMNLabel id="BPMNLabel_1" labelStyle="BPMNLabelStyle_1">
          <dc:Bounds height="14.0" width="3.0" x="108.0" y="78.0"/>
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
    <bpmndi:BPMNLabelStyle id="BPMNLabelStyle_1">
      <dc:Font name="arial" size="9.0"/>
    </bpmndi:BPMNLabelStyle>
  </bpmndi:BPMNDiagram>
```

I think I could implement a similar behaviour in GLSP by myself as I become very good in GLSP the last weeks ;-)

But I have two problems

1. How can I calculate the Width of a GLabel by its text? Is this possible at all? Or can I place a Label centered?
2. Is it possible to provide a GLable with multiple lines - and a corresponding GLabel editor?
